version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: devops_portfolio
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: devops_password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks: [app-net]

  web:
    build: ./app
    env_file: [.env]
    depends_on: [db]
    networks: [app-net]

  nginx:
    image: nginx:1.27-alpine
    depends_on: [web]
    ports: ["80:80"]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks: [app-net]

volumes:
  db_data:

networks:
  app-net:
    driver: bridge
